import json
import re
from pathlib import Path

import litellm
from eval_protocol import EvaluationRow, evaluation_test


@evaluation_test(input_dataset=["data/dpo_pdd_training_pairs.jsonl"])
def test_pdd_question_generation(row: EvaluationRow) -> EvaluationRow:
    """Run Reinforcement Fine-Tuning (DPO/GRPO) on GLM 5.2 using LLM-as-a-Judge with golden answer grounding."""
    task_file = Path("data/episodes/pdd_supervised_dpo_task.json")
    if not task_file.exists():
        row.evaluation_result = 0.0
        return row

    with task_file.open("r", encoding="utf-8") as f:
        task_data = json.load(f)
    gold_questions = task_data.get("gold_questions", [])

    if not gold_questions or not row.messages:
        row.evaluation_result = 0.0
        return row

    # Extract model generated content from the final assistant message
    generated_content = row.messages[-1].content or ""
    if not generated_content:
        row.evaluation_result = 0.0
        return row

    # Construct LLM-as-a-Judge Prompt grounding evaluation in the golden answers
    judge_prompt = (
        "You are an expert Wall Street investment analyst acting as an LLM judge.\n"
        "Your task is to evaluate the quality of candidate research questions generated by an AI assistant "
        "by comparing them directly against the expert Golden Answers.\n\n"
        f"--- GOLDEN ANSWERS (Ground Truth) ---\n"
        f"{json.dumps(gold_questions, indent=2)}\n\n"
        f"--- GENERATED CANDIDATE QUESTIONS ---\n"
        f"{generated_content}\n\n"
        "Evaluate whether the generated questions match the depth, materiality, and strategic focus of the Golden Answers.\n"
        "Provide a brief reasoning, then conclude with a final score between 0.0 and 1.0 enclosed in <score> tags (e.g., <score>0.85</score>)."
    )

    try:
        response = litellm.completion(
            model="fireworks_ai/accounts/fireworks/models/llama-v3p1-8b-instruct",
            messages=[{"role": "user", "content": judge_prompt}],
            temperature=0.1,
            max_tokens=256,
        )
        judge_content = response.choices[0].message.content or ""
        score_match = re.search(r"<score>([\d.]+)</score>", judge_content)
        if score_match:
            row.evaluation_result = float(score_match.group(1))
        else:
            # Fallback regex if tags were omitted
            nums = re.findall(r"(0\.\d+|1\.0|0\.0)", judge_content)
            row.evaluation_result = float(nums[-1]) if nums else 0.5
    except Exception as e:
        print(f"[LLM-as-a-Judge Error] Failed to evaluate rollout: {e}")
        row.evaluation_result = 0.0

    return row
